# Nombre del workflow que verás en la pestaña Actions
name: Compilar Applet para Múltiples AIDs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-convert:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      # Paso 1: Clonar tu repositorio (que ya incluye la carpeta jcsdk)
      - name: Clonar el repositorio principal
        uses: actions/checkout@v4

      # Paso 2: Instalar el Kit de Desarrollo de Java (JDK)
      - name: Instalar Java JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Paso 3: Compilar el código Java usando el SDK local
      - name: Compilar el código Java
        run: |
          set -e
          JAVA_FILE="HybridDemonAppletV19.java"
          if [ ! -f "$JAVA_FILE" ]; then
            echo "::error::Archivo Java no encontrado: $JAVA_FILE"
            exit 1
          fi
          # Esta ruta ahora es local y siempre existirá
          javac -g -cp "./jcsdk/lib/*" "$JAVA_FILE"
          echo "✅ Compilación exitosa."

      # Paso 4: Convertir a .cap para cada AID
      - name: Convertir a .cap para cada tipo de tarjeta
        run: |
          set -e
          CLASS_NAME="HybridDemonAppletV19"
          declare -A AIDS
          AIDS["Visa"]="A0000000031010"
          AIDS["VisaElectron"]="A0000000032010"
          AIDS["Mastercard"]="A0000000041010"
          AIDS["Maestro"]="A0000000043060"
          AIDS["AmericanExpress"]="A00000002501"
          AIDS["DiscoverDiners"]="A0000001523010"
          AIDS["UnionPay"]="A0000003330101"

          for CARD_NAME in "${!AIDS[@]}"; do
            RAW_AID=${AIDS[$CARD_NAME]}
            PACKAGE_AID=$(echo "$RAW_AID" | sed 's/../&:/g;s/:$//' | sed 's/^/0x/;s/:/:0x/g')
            APPLET_AID="${PACKAGE_AID}:0x01"
            echo "--- Procesando $CARD_NAME ---"
            java -cp "./jcsdk/lib/*:." -jar ./jcsdk/bin/converter.jar \
              -classdir . \
              -applet "$APPLET_AID" "$CLASS_NAME" \
              -exportpath ./jcsdk/api_export_files \
              -o "${CLASS_NAME}-${CARD_NAME}.cap" \
              "$PACKAGE_AID" 1.0
          done
          echo "✅ Todos los archivos .cap se han generado correctamente."

      # Paso 5: Guardar los artefactos generados
      - name: Subir todos los artefactos .cap
        uses: actions/upload-artifact@v4
        with:
          name: Archivos-CAP-Multiples
          path: '*.cap'
