# Nombre del workflow que verás en la pestaña Actions
name: Compilar Applet para Múltiples AIDs

# Esto hace que el workflow se ejecute cada vez que subes cambios
on:
  push:
    branches: [ "main" ]
  # También te permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  build-and-convert:
    # Usaremos una máquina virtual de Ubuntu para compilar
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código de tu repositorio
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      # Paso 2: Instalar el Kit de Desarrollo de Java (JDK)
      - name: Instalar Java JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # --- INICIO DE LA CORRECCIÓN DEFINITIVA ---
      # Paso 3: Instalar el Kit de Desarrollo de Java Card (Método Git Clone Optimizado)
      - name: Clonar Java Card SDK con Git (Shallow)
        run: |
          # Clonamos solo el último estado del repositorio (--depth 1).
          # Esto es más rápido y evita errores en entornos automáticos.
          git clone --depth 1 https://github.com/ph4r05/javacard-sdk-305.git
          # Movemos la carpeta clonada para que tenga el nombre que esperamos
          mv javacard-sdk-305 jcsdk
      # --- FIN DE LA CORRECCIÓN DEFINITIVA ---

      # Paso 4: Compilar el archivo .java
      - name: Compilar el código Java
        run: |
          JAVA_FILE_NAME="HybridDemonAppletV19.java"
          echo "Compilando $JAVA_FILE_NAME..."
          javac -g -cp ./jcsdk/api_export_files/api_classic.jar $JAVA_FILE_NAME

      # Paso 5: Convertir a .cap para cada AID de la lista
      - name: Convertir a .cap para cada tipo de tarjeta
        run: |
          CLASS_NAME=$(basename "HybridDemonAppletV19.java" .java)
          declare -A AIDS
          AIDS["Visa"]="A0000000031010"
          AIDS["VisaElectron"]="A0000000032010"
          AIDS["Mastercard"]="A0000000041010"
          AIDS["Maestro"]="A0000000043060"
          AIDS["AmericanExpress"]="A00000002501"
          AIDS["DiscoverDiners"]="A0000001523010"
          AIDS["UnionPay"]="A0000003330101"

          for CARD_NAME in "${!AIDS[@]}"; do
            RAW_AID=${AIDS[$CARD_NAME]}
            PACKAGE_AID=$(echo $RAW_AID | sed 's/../&:/g;s/:$//' | sed 's/^/0x/;s/:/:0x/g')
            APPLET_AID="${PACKAGE_AID}:0x01"
            echo "--- Procesando $CARD_NAME ---"
            java -jar ./jcsdk/bin/converter.jar \
              -classdir . \
              -applet $APPLET_AID $CLASS_NAME \
              -exportpath ./jcsdk/api_export_files \
              -o "${CLASS_NAME}-${CARD_NAME}.cap" \
              $PACKAGE_AID 1.0
          done

      # Paso 6: Guardar TODOS los archivos .cap generados
      - name: Subir todos los artefactos .cap
        uses: actions/upload-artifact@v4
        with:
          name: Archivos-CAP-Multiples
          path: '*.cap'
